### ISSUE TITLE
Multipart Insert Nano CouchDB

### ISSUE THREAD

**Issue by omeryousaf** [open-learning-exchange/PDFOptimizer#1]
The code, in app.js file of the repo, is working fine for downloading (writing to disk) pdf based documents (couchdb documents with a pdf attachment), as well as for converting the pdfs to images, but it gives one of the following two errors while trying to upload the pdf and images back for some of the documents:
(1)
{ [Error: function_clause]
name: 'Error',
error: 'unknown_error',
reason: 'function_clause',
scope: 'couch',
statusCode: 500,
request:
{ method: 'PUT',
headers: { 'content-type': 'multipart/related' },
uri: 'http://127.0.0.1:5984/resources/908cff949cfafb0f
c17c804509004ab5',
multipart: [ [Object], {}, {}, {}, {}, {}, {}, {}, {}, {}, {} ] },
headers:
{ date: 'Fri, 23 Jan 2015 14:57:55 GMT',
'content-type': 'text/plain; charset=utf-8',
'cache-control': 'must-revalidate',
statusCode: 500,
uri: 'http://127.0.0.1:5984/resources/908cff949cfafb0f
c17c804509004ab5' },
errid: 'non_200',
description: 'couch returned 500' }

(2)
{ [Error: error happened in your connection]
name: 'Error',
scope: 'socket',
errid: 'request',
code: 'ECONNRESET',
errno: 'ECONNRESET',
syscall: 'read',
description: 'read ECONNRESET',
stacktrace:
[ 'Error: read ECONNRESET',
' at errnoException (net.js:905:11)',
' at TCP.onread (net.js:559:19)' ] }

Any help would be appreciated. Here is the code doing the upload:
resources.multipart.insert(body, files, resId, function(err, body) {
if (err) {
mainCallback(err);
return;
}
});
where 'body' is the document with the pdf attachment, 'files' are all files that should get inserted as attchments to the document through the upload, 'resId' is the id of the document. I guess my return statement is redundant cuz the callback preempts it.

**Comment by omeryousaf** [comment]
The pdfs I was using for testing can be found here: https://drive.google.com/folderview?id=0BxWXPOnl5kJZQkRqTXFidlJpam8&usp=sharing
It crashed most of the times at the pdf title 'Homework 3' and one titled 'Validation Functions'

**Comment by rjcorwin** [comment]
@omeryousaf I wonder if the error has something to do with the CouchDB install, perhaps a setting in that CouchDB's configuration. Have you tried targeting another CouchDB? Try one of the QA CouchDBs on Hammock such as http://earthbell-qa.ole.org:5985/.

**Comment by omeryousaf** [comment]
@rjsteinert,  @Adnan-Khalil has made a fix to this issue (updating the paths in environment variable with path for npm and nodejs executables before they are referenced in the installer. Check it out and let us know if it works smoothly now.

**Comment by omeryousaf** [comment]
Tried other couchdb servers, issue persists.
